// GENERATED by scripts/embed-clips.mjs — do not edit by hand.
export const CLIPS = [
  {
    "id": "intro1",
    "name": "片头 1",
    "ext": ".mp4",
    "bytes": 453662,
    "sha256": "6dfd80736d025b6e",
    "b64": 604884
  },
  {
    "id": "intro2",
    "name": "片头 2",
    "ext": ".mp4",
    "bytes": 1161694,
    "sha256": "42c441d18a1db676",
    "b64": 1548928
  },
  {
    "id": "intro3",
    "name": "片头 3",
    "ext": ".mp4",
    "bytes": 1159692,
    "sha256": "665295bf52a5293e",
    "b64": 1546256
  },
  {
    "id": "intro4",
    "name": "片头 4",
    "ext": ".mp4",
    "bytes": 13269084,
    "sha256": "b330f915cdddbe82",
    "b64": 17692112
  }
]
